package tech.nodex.example_springboot_restful.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return get("id");
	}

	public void setStoreId(java.lang.Long storeId) {
		set("store_id", storeId);
	}

	public java.lang.Long getStoreId() {
		return get("store_id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPics(java.lang.String pics) {
		set("pics", pics);
	}

	public java.lang.String getPics() {
		return get("pics");
	}

	public void setProductDesc(java.lang.String productDesc) {
		set("product_desc", productDesc);
	}

	public java.lang.String getProductDesc() {
		return get("product_desc");
	}

	public void setProductDetail(java.lang.String productDetail) {
		set("product_detail", productDetail);
	}

	public java.lang.String getProductDetail() {
		return get("product_detail");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
